### ISSUE TITLE
Neo4j browser causing the system to freeze

### ISSUE THREAD

**Issue by mariosk89** [graphadvantage/neo4j-browser-images#2]
Hi, I'm using your script for a small project that I'm working on. 
Most of the times, when I'm trying to drag a node inside the graph, the whole system on my machine freezes.
Removing the two entries from the script will fix the issue (but it will obviously remove the pictures from within my nodes)
Is this something that anyone else has faced?
Any ideas on how to fix this?

**Comment by graphadvantage** [comment]
Hi 
How large are the images you are trying to use? Try to not exceed about 100x100.
You should see reasonable performance in for visualizations up to around 100 nodes.  
Each image has to be individually loaded from the url.  I use Chrome because it's pretty fast.

update:

I just verified with the latest build of neo4j-browser.

try adding this to a node:

image_url: http://i.annihil.us/u/prod/marvel/i/mg/1/60/5239bf9387906/standard_fantastic.jpg

this is 250x250, works
