### ISSUE TITLE
show images stored locally on computer

### ISSUE THREAD

**Issue by maribeth73** [graphadvantage/neo4j-browser-images#4]
When creating a node with an image in the background, Instead of using a web-hosted image, such as 
SET n.image_url = "http://myimage.png"
I would like to link to a local image, such as; 
SET n.image_url = "file:///home/Pictures/myimage.jpg"

However, I tried this and it does not seem to work. Is there a way to get local images to show as node backgrounds?

**Comment by graphadvantage** [comment]
Hi Maribeth

This is a CORS issue - .js wants to access files from a web server.  Best to publish your images on a web server somewhere, even localhost will work.

But since you are running neo4-browser locally, the best workaround is to include your images in the neo4j-browser /images  directory and access them by prepending assets/ to the image_url property path.  This makes the images accessible within the context of the project.

see the index.html file in neo4j-browser for reference

```
MERGE (n:MyImageNode) 
SET n.image_url='assets/images/myimage.png'
RETURN n
```
